apiVersion: v1
kind: Service
metadata:
  name: "the-one"
  labels:
    app: "the-one"
    chart: {{ template "more-helm-stuff.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 92
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: "the-one"
    release: {{ .Release.Name }}
