apiVersion: v1
kind: Service
metadata:
  name: "v1"
  labels:
    app: "v1"
    chart: {{ template "more-helm-stuff.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ template "more-helm-stuff.name" . }}
    release: {{ .Release.Name }}
