apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-time-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: date-time-ui
  template:
    metadata:
      labels:
        app: date-time-ui
    spec:
      containers:
      - image: index.docker.io/jvermeir/date-time:latest
        name: date-time-ui
        ports:
        - containerPort: 8000
