apiVersion: v1
kind: Service
{{- $appName := "v2" -}}
metadata:
  name: {{ $appName }}
  labels:
    app: {{ $appName }}
    chart: {{ template "more-helm-stuff.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 93
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ $appName }}
    release: {{ .Release.Name }}
